### ISSUE TITLE
台词语音顺序问题

### ISSUE THREAD

**Issue by ilhmtfmlt2** [Alex-McAvoy/Legends-of-the-Three-Kingdoms-Offline-Assistant#1]
袁术的【同疾】技能存在语音和台词顺序颠倒的问题。

**Comment by Alex-McAvoy** [comment]
已修复，新版本见 [v0.1.1-alpha](https://github.com/Alex-McAvoy/Legends-of-the-Three-Kingdoms-Offline-Assistant/releases/tag/v0.1.1-alpha)
